### ISSUE TITLE
Improve documentation of configuration options

### ISSUE THREAD

**Issue by TillaTheHun0** [doitadrian/adio#7]
## This is:
- Feature request

## Detailed Description
I had to do some digging, in the source code, to figure out how to work through some issues, in particular how to enable `adio` to handle TypeScript files. In that process, I found some really helpful configuration options that also weren't documented.

## Possible Solution
Update the README. There looks to be a section marked off for this, but was never populated.

**Comment by doitadrian** [comment]
Thanks for the issue @TillaTheHun0. 

You're absolutely right :)

Will try to create a proper documentation during the week.

Thanks a lot! :)

**Comment by TillaTheHun0** [comment]
@doitadrian thanks! I don't know if you say, but i've opened a PR that attempts to solve this issue #8 . Let me know if that works, of if you'd like any changes :)

**Comment by TillaTheHun0** [comment]
Done in #8 . I believe this can be closed.
