### ISSUE TITLE
Enable Adio to handle certain syntax out of the box

### ISSUE THREAD

**Issue by TillaTheHun0** [doitadrian/adio#9]
## This is:
- Feature request

## Detailed Description
I love that the `parser` api is just a passthrough to `@babel/parser` options, as that makes it super easy to augment the behavior of babel. However, I had to do a little more than expected to get `adio` working.

In order for `adio` to handle `TypeScript` files for example, I had to add the `typescript` parser plugin in the `.adiorc`. This is only kosher, since this api is truly a passthrough to `@babel/parser`, but it would be great if TypeScript syntax, among other common syntax like `classProperties`, were handled out of the box with `adio`

## Possible Solution
Add commonly used babel plugins, by default, to pass along to `@babel/parser`, and merge that with incoming configuration.

**Comment by doitadrian** [comment]
I think this makes sense.

Thanks a lot for the suggestion, will check it out.

**Comment by TillaTheHun0** [comment]
@doitadrian thanks! I don't know if you saw, but i've opened a PR that attempts to solve this issue #10  . Let me know if that works, or if you'd like any changes :)

**Comment by TillaTheHun0** [comment]
Done in #10 . I believe this can be closed.
